### ISSUE TITLE
There is another kSar fork.

### ISSUE THREAD

**Issue by aero** [ppalucha/ksar2#1]
Hello
I just found another kSar fork ( https://github.com/vlsi/ksar )
It alsoe seemed to be working fine on RHEL/Centos 7.x.

**Comment by ppalucha** [comment]
Yes, I found it only after I created my fork ;-)

**Comment by Pitterling** [comment]
@ppalucha I'm contributing to the other fork and just found this one here. I see you are actively maintaining your fork. So, why not combining work forces and concentrate expertise instead of developing the same things again and again? BR Peter

**Comment by ppalucha** [comment]
Hi,
Generally, a good idea. However: 

- I see you have some ambitious plans for your fork, like migrating to JavaFX8; you already migrated to more modern build system; your binaries require Java 8. My intention was rather to keep the ksar usable without such drastic changes. You should still be able to run my fork on old legacy UNIX with ancient version of Java. So it looks like our forks may have a little different goals.
- What is more important, I won't be able to contribute too actively for the next half a year at least.

So I appreciate the proposition, but I cannot be involved in the nearest future... Best of luck with your fork!

**Comment by Pitterling** [comment]
fair enough, just wanted to make you aware again .. Best of luck with your fork as well !!
