### ISSUE TITLE
Looking for command line feature for generating reports in PNG

### ISSUE THREAD

**Issue by chikkalain** [ppalucha/ksar2#10]
In older version , I found report generation in PNG and JPEG ,But the new version I did not find these feature. I am looking similar NMON command line for KSAR also .

https://nmonvisualizer.github.io/nmonvisualizer/commandline.html

5.0.6 has these feature

https://en.wikipedia.org/wiki/Ksar_(Unix_sar_grapher)

**Comment by ppalucha** [comment]
There's a report generation in PDF. You can also export single graph to CSV/JPG/PNG.
