### ISSUE TITLE
cant automatic result output jpg graph in linux terminal

### ISSUE THREAD

**Issue by lubry** [ppalucha/ksar2#2]
i have problem with this, i try to using command 
`java -jar kSar2-0.0.2.jar -input '/home/centos/sa05.txt' -outputJPG /home/centos/Pictures/ksar/`
why not automatic result output jpg graph? i have try in kSar-5.0.6, no problem. any solution?

**Comment by ppalucha** [comment]
Hi,
There's no trace of such option in the 5.1 beta source code, which kSar2 is based on. But generally the command line arguments parsing sucks in current version and should be improved. The only problem is that Java is lacking usable built-in arguments parser, so I need to choose one of 100 available external libraries...
I will mark it as "enhancement".
Regards
Paweł

**Comment by ppalucha** [comment]
Current git HEAD version includes new options handling with -p / -c to export graphs as PDF / CSV file. I hope this solves the issue.
